---
title: Installiere ein Softwarepaket auf dem Raspberry Pi
hero_image: images/banner.png
description: Lerne, wie du ein Softwarepaket auf dem Raspberry Pi installierst
theme: rot #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 #possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: ""
site_areas:
steps:
  - 
    title: Einleitung
